dataset:
    preprocess: False
    data_dir: '/data/anitha/label_free/image_tile_256-256_step_256-256'
    input_channels: [3]
    target_channels: [0]
    split_by_column: sample_num
    split_ratio:
        train: 0.7
        val: 0.15
        test: 0.15
    height: 256
    width: 256
verbose: 10
trainer:
    model_dir: '/home/krishnan/models_labelfree/tile256_bs16_mse'
    batch_size: 32
    max_epochs: 200
    metrics: coeff_determination
    loss: mean_squared_error
    callbacks:
        EarlyStopping:
            mode: min
            monitor: val_loss
            patience: 50
            verbose: True
        ModelCheckpoint:
            mode: min
            monitor: val_loss
            save_best_only: True
            verbose: True
        TensorBoard:
            histogram_freq: 0
            verbose: True
    optimizer:
        lr: 0.0001
        name: Adam
network:
    class: Image2DToVectorNet
    num_input_channels: 4
    data_format: 'channels_first'
    height: 256
    width: 256
    batch_norm: True
    pooling_type: conv
    res_pool_type: max
    filter_size: 3
    activation:
        type: relu
    dropout: 0.2
    num_initial_filters: 16
    num_convs_per_block: 2
    block_sequence: conv-activation-bn
    residual: True
    dense:
        type: conv
        dropout: 0.4
        num_units: [512, 256, 128]
        regression_length: 32
        kernel_regularizer:
            type: l2
            lambda: 0.001
    final_activation: linear
