# Hydra configuration matching lightning-hydra-template

run:
  dir: ${paths.log_dir}/${task_name}/runs/${now:%Y-%m-%d_%H-%M-%S}

sweep:
  dir: ${paths.log_dir}/${task_name}/multiruns/${now:%Y-%m-%d_%H-%M-%S}
  subdir: ${hydra.job.num}

job:
  name: ${task_name}
  chdir: False

verbose: False
